services:
  meilisearch:
    image: getmeili/meilisearch:latest
    volumes:
      - ./data.ms:/data.ms
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-ms}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700"]
      interval: 10s
      timeout: 5s
      retries: 5

  meilisearch-admin:
    image: riccoxie/meilisearch-ui:latest
    ports:
      - "24900:24900"
    depends_on:
      - meilisearch

  meilisync:
    platform: linux/amd64
    image: long2ice/meilisync
    volumes:
      - ./config.yml:/meilisync/config.yml
      - ./progress.json:/meilisync/progress.json
    depends_on:
      - meilisearch
